# Generated by Django 4.2.4 on 2023-08-31 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterrole',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user', to='myapp.masterrole'),
        ),
        migrations.AddField(
            model_name='masterrole',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_user', to='myapp.masterrole'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
