# Generated by Django 4.2.4 on 2023-08-31 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_bought_created_by_bought_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user', to='myapp.categories'),
        ),
        migrations.AddField(
            model_name='categories',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_user', to='myapp.categories'),
        ),
    ]
