# Generated by Django 4.2.4 on 2023-08-31 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_product_created_user_product_modified_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_category', to=settings.AUTH_USER_MODEL),
        ),
    ]
