# Generated by Django 4.2.4 on 2023-08-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_categories_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='modified_by',
        ),
    ]
