# Generated by Django 4.2.4 on 2023-09-01 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_customuser_created_by_customuser_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterrole',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rolemaster', to='myapp.masterrole'),
        ),
        migrations.AlterField(
            model_name='masterrole',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterrole',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_rolemaster', to='myapp.masterrole'),
        ),
    ]
