# Generated by Django 4.2.4 on 2023-09-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_masterrole_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterrole',
            old_name='created_by',
            new_name='created_role_by',
        ),
        migrations.RenameField(
            model_name='masterrole',
            old_name='modified_by',
            new_name='modified_role_by',
        ),
    ]
