# Generated by Django 4.2.4 on 2023-09-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_masterrole_created_role_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrole',
            name='created_by',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='masterrole',
            name='modified_by',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
