# Generated by Django 4.2.4 on 2023-09-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_masterrole_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterrole',
            old_name='created_by_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='masterrole',
            old_name='modified_by_id',
            new_name='modified_by',
        ),
    ]
