# Generated by Django 4.2.4 on 2023-09-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_masterrole_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterrole',
            name='modified_by',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
